name: Empty Wallet Build
on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Repair and Clean
        run: |
          flutter clean
          flutter create --platforms android,web .
          flutter pub get

      - name: Build Web
        run: |
          # The base-href is critical for GitHub Pages
          flutter build web --release --base-href "/${{ github.event.repository.name }}/" --no-tree-shake-icons

      - name: Build APK
        run: |
          flutter build apk --split-per-abi
          
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: all-release-apks
          path: build/app/outputs/flutter-apk/*.apk

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
