name: Empty Wallet Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Repair Android Project
        run: flutter create --platforms android .

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --split-per-abi
          
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: all-release-apks
          path: build/app/outputs/flutter-apk/*.apk
